# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("django_sshworker", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_sshworker.Worker",
            ),
        )
    ]
