# Generated by Django 2.2.28 on 2022-10-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sshworker', '0003_auto_20220203_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
